services:
  scheduler:
    image: mageai/mageai
    volumes:
      - "./scheduler_data:/home/src"
      - "~/.dbt:/root/.dbt" 
    ports:
      - "6789:6789"
    command: /app/run_app.sh mage start scheduler
