demo:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: VVANKYF-ZH08496
      user: GIANMARTIN
      role: ACCOUNTADMIN
      password: j9SMJ3B5NuetucL
      database: NY_TAXI
      warehouse: COMPUTE_WH
      schema: SILVER
      threads: 4
      client_session_keep_alive: False